import { Bai_Jamjuree } from 'next/font/google'
import { Providers } from './providers'

const bai_jamjuree = Bai_Jamjuree({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: 'Ecthon Almeida',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bai_jamjuree.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
